// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCyzpjDurOzg2GSttzsU5gubk67sOtqVo',
    appId: '1:344679474914:web:bf484e499a92329968a0bb',
    messagingSenderId: '344679474914',
    projectId: 'warehouse-project-56bf2',
    authDomain: 'warehouse-project-56bf2.firebaseapp.com',
    storageBucket: 'warehouse-project-56bf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYiWWAAUn8_4jIeQMemx8uO3KpVhiBD5g',
    appId: '1:344679474914:android:dd3b43ab29f7d60968a0bb',
    messagingSenderId: '344679474914',
    projectId: 'warehouse-project-56bf2',
    storageBucket: 'warehouse-project-56bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAERE5DYkAkcOoHlpu1AMYe4ogy73dK6ME',
    appId: '1:344679474914:ios:9a88eb682e1e787c68a0bb',
    messagingSenderId: '344679474914',
    projectId: 'warehouse-project-56bf2',
    storageBucket: 'warehouse-project-56bf2.appspot.com',
    iosBundleId: 'com.example.warehouseAdminProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAERE5DYkAkcOoHlpu1AMYe4ogy73dK6ME',
    appId: '1:344679474914:ios:9a88eb682e1e787c68a0bb',
    messagingSenderId: '344679474914',
    projectId: 'warehouse-project-56bf2',
    storageBucket: 'warehouse-project-56bf2.appspot.com',
    iosBundleId: 'com.example.warehouseAdminProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCyzpjDurOzg2GSttzsU5gubk67sOtqVo',
    appId: '1:344679474914:web:2520c0df8c9d03c268a0bb',
    messagingSenderId: '344679474914',
    projectId: 'warehouse-project-56bf2',
    authDomain: 'warehouse-project-56bf2.firebaseapp.com',
    storageBucket: 'warehouse-project-56bf2.appspot.com',
  );
}
